/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameTypesRouteImport } from './routes/game-types'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as TablesRouteImport } from './routes/tables'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameTypesRoute = GameTypesRouteImport.update({
  id: '/game-types',
  path: '/game-types',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesRoute = TablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game-types': typeof GameTypesRoute
  '/players': typeof PlayersRoute
  '/reports': typeof ReportsRoute
  '/sessions': typeof SessionsRoute
  '/tables': typeof TablesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game-types': typeof GameTypesRoute
  '/players': typeof PlayersRoute
  '/reports': typeof ReportsRoute
  '/sessions': typeof SessionsRoute
  '/tables': typeof TablesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game-types': typeof GameTypesRoute
  '/players': typeof PlayersRoute
  '/reports': typeof ReportsRoute
  '/sessions': typeof SessionsRoute
  '/tables': typeof TablesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/game-types' | '/players' | '/reports' | '/sessions' | '/tables'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/game-types' | '/players' | '/reports' | '/sessions' | '/tables'
  id:
    | '__root__'
    | '/'
    | '/game-types'
    | '/players'
    | '/reports'
    | '/sessions'
    | '/tables'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameTypesRoute: typeof GameTypesRoute
  PlayersRoute: typeof PlayersRoute
  ReportsRoute: typeof ReportsRoute
  SessionsRoute: typeof SessionsRoute
  TablesRoute: typeof TablesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-types': {
      id: '/game-types'
      path: '/game-types'
      fullPath: '/game-types'
      preLoaderRoute: typeof GameTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables': {
      id: '/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof TablesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameTypesRoute: GameTypesRoute,
  PlayersRoute: PlayersRoute,
  ReportsRoute: ReportsRoute,
  SessionsRoute: SessionsRoute,
  TablesRoute: TablesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
